fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib
      ref: '4.6.0'
    concat:
      repo: git://github.com/puppetlabs/puppetlabs-concat
      ref: '1.2.1'
  symlinks:
    openvpn: "#{source_dir}"

