---
language: ruby
sudo: false
cache: bundler
bundler_args: --without development
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
env:
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  fast_finish: true
notifications:
  email: false
  on_success: always
  on_failure: always
